version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:731660006307:task-definition/hello-world-task:1"
        LoadBalancerInfo:
          ContainerName: "hello-world-container"
          ContainerPort: "80"
        PlatformVersion: "LATEST"
